# Generated by Django 6.0.3 on 2026-04-30 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lectures.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture'),
            preserve_default=False,
        ),
    ]
