# Generated by Django 6.0.3 on 2026-04-30 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_professor_student_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.professor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lectures.lecture'),
        ),
    ]
