# Generated by Django 6.0.3 on 2026-04-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={},
        ),
        migrations.AlterModelManagers(
            name='guest',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='password',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
